#!/bin/bash

echo "IP-server"; read -r ip ; \
echo "internal_port"; read -r in ; \
echo "external_port"; read -r ex ; \
openstack floating ip list | grep 185 | awk -F '|' '{print $2}' | awk '{print substr($1,0)}' > float.txt &&
echo "$ex" '>' "$ip":"$in" > description.txt &&
openstack port list | grep "$ip" | awk -F '|' '{print $2}' | awk '{print substr($1,0)}' > IPP.txt &&
openstack floating ip port forwarding create --internal-ip-address "$ip" --port "$(< IPP.txt)" --internal-protocol-port "$in" \
--external-protocol-port "$ex" --protocol tcp "$(< float.txt)" &&
openstack floating ip set "$(< float.txt)" --description "$(< description.txt)" &&
echo "Success port forwarding"
